#!/usr/bin/env bash

# TODO: temporary, needs to be set by a project_config
DOCUMENT			:= document

# LATEX/PANDOC DOCKER SWITCH
# if docker images are set up for running latex, revert to those.  Otherwise 
# invoke latexmk/docker natively
# (LATEX_PREFIX is either "${LATEX_DOCKER} " or empty)
LATEX_DOCKER		:= texdock
LATEX_PREFIX		:= $(shell which ${LATEX_DOCKER} >/dev/null && echo "${LATEX_DOCKER} ")
LATEX				:= ${LATEX_PREFIX} latexmk

# TODO: this is supposed to come from a project_config file, once that is 
# implemented
TEX_ENGINE			:= pdflatex

SCRIPT_INCLUDE_CHAPTERS	:= ${DIR_SCRIPTS}/include_chapters.py


############################################################
# VARIABLES
############################################################

DIR_SRC				:= src

SRC_TEX				:= $(wildcard ${DIR_SRC}/*/*.tex)
DIR_TEX_OUT			:= tex_out


############################################################
# TARGETS
############################################################

all: ${DOCUMENT}.pdf

${DOCUMENT}.pdf:	${SRC_TEX} include_chapters
	@echo "Creating the document..."
	${LATEX} -output-directory=${DIR_TEX_OUT} -${TEX_ENGINE} main.tex
	@cp ${DIR_TEX_OUT}/main.pdf ${DOCUMENT}.pdf

.PHONY: include_chapters
include_chapters:	${SRC_TEX}
	@echo "Scanning for chapters..."
	@python3 ${SCRIPT_INCLUDE_CHAPTERS}

